### ISSUE TITLE
Cannot handle exception by WSGI middlewares

### ISSUE THREAD

**Issue by meyt** [pylover/nanohttp#15]
WSGI middlewares for debugging like `werkzeug` doesn't work currently, and exceptions handled by `nanohttp`. 

Based this sample:
```
from werkzeug.debug import DebuggedApplication
from nanohttp import Controller, configure, html
class Root(Controller):
    @html
    def index(self):
        x = 1 / 0
        return 'test'
configure()
app = DebuggedApplication(Root().load_app(), evalex=True)
```
results show `nanohttp` exception handler instead of `werkzeug` debugger.

**Comment by pylover** [comment]
Yes, I should make the  `_handle_exception` method optional.

**Comment by meyt** [comment]
Problem still alive, and when running that code this warning shown by `werkzeug.debug`:
`Debugging middleware caught exception in streamed response at a point where response headers were already sent.`
I fix it at last commit.

**Comment by pylover** [comment]
This a normal behaviour. The `nanohttp` supports HTTP streaming. It means the exception may occur after sending the response header.

A bad practice to get rid of this is buffering the whole response in the memory, and serving it at once.
This is what the most HTTP frameworks are doing.

So, if you don't want to use the chunked response streaming, just user `return` instead of `yield`.

**Comment by pylover** [comment]
Our nanohttp applications are BDD and have the 100% code coverage.

So, we never get 500 after `start_response`. That's why we're using the nanohttp.

**Comment by pylover** [comment]
If you carefully check this code:

```python
        try:
            self._hook('begin_request')
            if self.__root__.__remove_trailing_slash__:
                ctx.path = ctx.path.rstrip('/')

            result = self.__root__(*ctx.path.split('?')[0][1:].split('/'))
            if result:
                resp_generator = iter(result)
                buffer = next(resp_generator)
            else:
                resp_generator = None

        except Exception as ex:
            self.__logger__.exception('Exception while handling the request.')
            try:
                status, resp_generator = self._handle_exception(ex)
            except NotImplementedError:
                raise ex

        finally:
            self._hook('begin_response')

            if context.response_cookies:
                for cookie in context.response_cookies:
                    ctx.response_headers.add_header(*cookie.http_set_cookie())
            start_response(status, ctx.response_headers.items())
```

If the exception is raised at the first iteration of the response generator, it will be raised to the parent application.

**Comment by pylover** [comment]
Toughts?
