### ISSUE TITLE
Jsonilizing time objects fails with Segmentation fault: 11

### ISSUE THREAD

**Issue by eteamin** [pylover/nanohttp#38]
from datetime import time

    from nanohttp import Controller, RestController, html, json, quickstart

    class ObjectControllers(RestController):
        @json
        def get(self, obj_id: int = None):
            return dict(some_key=time(15, 15, 15))

    class Root(Controller):
        objects = ObjectControllers()

        @html
        def index(self):
            yield

Serving using `nanohttp module_name` and visiting http://localhost:8080/objects kills the server with a one line log: 

> Segmentation fault: 11

Are we dealing with resource constraints due to an infinite loop or something?

**Comment by pylover** [comment]
It depends on the `ujson` behavior.
