### ISSUE TITLE
Feature Request: More customization for error handling

### ISSUE THREAD

**Issue by meyt** [pylover/nanohttp#9]
At current behavior, when using `request_error` hook it returns `text/plain` content type with prepended `Internal Server Error` message. But i want an HTML page without any extra things.
P.S: It's clear to us, Errors are important, specially if we have sensitive clients.

**Comment by pylover** [comment]
Set the response content type to anything you want and return the error page

**Comment by pylover** [comment]
You can set the content type on this hook simply bu setting: `context.response_content_type = 'application/json'`.

Also, you may override the `Controller._handle_exception` method. which returns status code and resp.

I think that's enough to customize the error response. if not, please let I know.

**Comment by meyt** [comment]
This  code `context.response_content_type = 'application/json'` actually doesn't work, because `_handle_exception` just accept `application/json` anything else return as `text/plain`.
Also there is a little bit confusing situation, if hook defined for handling errors, obviously overriding that not good choice, and make this question: What the reason to using hook? _just changing description of response?!_

**Comment by pylover** [comment]
No, _handle_exception is not a hook. you can override it to do whatever you want

**Comment by meyt** [comment]
@pylover sorry, mistyping, checkout last updated comment.
